[build]
  base = "web"
  publish = "."
  command = "echo 'Static Site - No Build Needed'"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  PIPENV_IGNORE_VIRTUALENVS = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
